default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: localhost

development:
  <<: *default
  database: aws_app_development

test:
  <<: *default
  database: aws_app_test

production: 
  adapter: mysql2 
  encoding: utf8 
  database: cows_production
  username: <%= ENV['CAP_DB_USER'] %>
  password: <%= ENV['CAP_DB_PASS'] %>
